-- Tabla de empresas
CREATE TABLE empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR NOT NULL,
  logo_url VARCHAR,
  estado VARCHAR DEFAULT 'Activo',
  ultima_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::text, NOW()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::text, NOW())
);

-- Tabla de resumen de empresa
CREATE TABLE empresa_resumen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  personal INTEGER,
  areas INTEGER,
  actividad INTEGER,
  UNIQUE(empresa_id)
);

-- Tabla de estadísticas
CREATE TABLE empresa_estadisticas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  tipo VARCHAR NOT NULL,
  valor VARCHAR NOT NULL,
  UNIQUE(empresa_id, tipo)
);

-- Tabla de servicios principales
CREATE TABLE servicios_principales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  servicio VARCHAR NOT NULL
);

-- Políticas de seguridad
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresa_resumen ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresa_estadisticas ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios_principales ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública
CREATE POLICY "Permitir lectura pública de empresas" ON empresas
  FOR SELECT USING (true);

CREATE POLICY "Permitir lectura pública de resumen" ON empresa_resumen
  FOR SELECT USING (true);

CREATE POLICY "Permitir lectura pública de estadísticas" ON empresa_estadisticas
  FOR SELECT USING (true);

CREATE POLICY "Permitir lectura pública de servicios" ON servicios_principales
  FOR SELECT USING (true);

-- Índices para optimización
CREATE INDEX idx_empresas_nombre ON empresas(nombre);
CREATE INDEX idx_empresas_estado ON empresas(estado);
CREATE INDEX idx_estadisticas_tipo ON empresa_estadisticas(tipo); 